### ISSUE TITLE
No file selected message stays right to the button, even after file has been selected ...

### ISSUE THREAD

**Issue by thomiel** [SteveSandersonMS/BlazorInputFile#38]
... following your blog post https://blog.stevensanderson.com/2019/09/13/blazor-inputfile/

using Blazor wasm .NET 3.1

**Comment by astevens8182** [comment]
I am also having the same issue, I had it working and then all of a sudden it stopped. I did not change any code related to the input component as far as I can remember

**Comment by craigbrown** [comment]
I'm having this issue too with Server-Side Blazor in .NET Core 3.1.

**Comment by LaurenceFrost** [comment]
I have the same issue. Server Side Blazor, Chrome, and using v0.2.0. This issue was not there in 0.1.0-preview-00002. It has only started happening since 0.2.0.

Other than the "No file selected" message, the component seems to function correctly.

Hopefully this information is useful.

**Comment by robertsundstrom** [comment]
I experience the same problem.

**Comment by craigbrown** [comment]
It looks like this bug was introduced in pull request #23 if that helps.

**Comment by astevens8182** [comment]
I have recently found out that the bug no longer exists when I deployed my site to Azure it only seems to be happening in debug

**Comment by RayKoopa** [comment]
Still happens to me, 0.2.0, .NET Core 3.1 in Edge-Chromium 83

**Comment by frankfhoch** [comment]
Still happening to me as well. Also in Release (and also deployed on Azure).

**Comment by Tharindu6516** [comment]
I'm experiencing the same problem. Even on Azure. Some files are accepted some arent. Not surer whether it hapens when saving image as string;

**Comment by craigbrown** [comment]
You can work around this by changing the package version to `0.1.0-preview-00002`, using CSS to remove the "No file selected" prompt and creating your own one, or if you're using .NET 5 you can just use the built-in `InputFile` component instead of this one. 

Since it is now built in to the framework I doubt there will be any more updates to this package.
